### ISSUE TITLE
Design Brief

### ISSUE THREAD

**Issue by SN1GZ** [Aurora12SDD2019/at3-major-project-SN1GZ#5]

**Comment by SN1GZ** [comment]
The Restaurant at the End of the Universe is losing customers and wants to attract more by providing a simple computer game for people to play while sitting around eating and drinking. They are not really sure what they want, but it has to be simple, easy to learn and engaging.  They have in mind a ‘space invaders’ type game but are open to suggestions. 
They also have in mind a leader board with rewards for the high score of the month, the high score of the year and an all-time high score. 
The leader board should be able to be viewed and sorted on various criteria (eg. score, username, number of games played etc.)

•	A design brief for the client including:
o	work agreement outlining the agreed needs of the client and outcomes of the project
o	identification of social, ethical and legal issues that may arise from the project and recommending steps to address them
o	proposed solution including storyboards
o	licence agreement

**Comment by ProfStick** [comment]
I can't see that you have done any work on this :( Where is the actual design brief?

**Comment by SN1GZ** [comment]
What do you mean design brief sir? Like as in what the person wants the
program to do or act? I'm confused I thought I've done everything...

**Comment by ProfStick** [comment]
Are you able to meet me in the SDD room because I can’t find some of the stuff

Dr G

Dr Geoff Goldrick
Science and Software
0409811994
[aurora tagline logo]<http://www.aurora.nsw.edu.au/>
